#配置文件版本 请勿修改
Version: 1.0

#绑定显示样式
Style:
  #隐藏玩家名称
  HideName: false
  #到期时间格式
  DateFormat: 'yyyy-MM-dd HH:mm:ss'

#绑定标签处理
#检查操作 检索所有标签
#绑定操作 使用第一个标签
Tag:
  Bind:
  - '§6喵式绑定'
  - '§6灵魂绑定'
  - '§6SoulBound'
  TimeBind:
  - '§6到期时间'
  BindOnPickup:
  - '§4拾取后绑定'
  BindOnUse:
  - '§4使用后绑定'
  BindOnEquip:
  - '§4装备后绑定'

#检查装备栏
CheckArmor:
  #特殊命令(一些可以直接装备的命令)
  Command:
  - '/hat'

#设置
Setting:
  #死亡不掉落绑定物品
  #注意: 前提是服务器开启死亡掉落 不然全部不会掉落
  KeepOnDeath: true
  #不允许丢弃
  PreventDrop: true
  #丢弃后删除
  DeleteOnDrop: false
  #是否允许放到容器里
  AllowStore: true


