#配置文件版本 请勿修改
Version: 1.0

#绑定显示样式
Style:
  #隐藏玩家名称
  HideName: false
  #到期时间格式
  DateFormat: 'yyyy-MM-dd HH:mm:ss'

#绑定标签处理
#注意 检查标签为全部 绑定标签为第一个
Tag:
  Bind:
  - '§6喵式绑定'
  - '§6灵魂绑定'
  - '§6SoulBound'
  TimeBind:
  - '§6到期时间'
  BindOnPickup:
  - '§4拾取后绑定'
  BindOnUse:
  - '§4使用后绑定'
  BindOnEquip:
  - '§4装备后绑定'

#设置
Setting:
  #死亡不掉落绑定物品
  #注意: 前提是服务器开启死亡掉落 不然全部不会掉落
  KeepOnDeath: true
  #不允许丢弃
  PreventDrop: true
  #丢弃后删除
  DeleteOnDrop: false
  #是否允许放到容器里
  AllowStore: true


